#!/usr/bin/env python3
from nfa import *
from nfa_path import *
from MEGALIB import *
from parse_re import *
import sys

regex = sys.argv[1]
if len(regex)>1:
	string = parseExpr(sys.argv[1])
elif len(regex) == 1:
	string = parseExpr(sys.argv[1])
else:
	string = '(epsilon)'
try:
	string2 = sys.argv[2]
except IndexError:
	string2 = input()


NFA5 = re_to_nfa(string)
if match_string(NFA5, string2)[0] == True:
	print(string2)